### ISSUE TITLE
Unknown Service - Amazon Priester Music

### ISSUE THREAD

**Issue by LSchuetzi84** [SpoturDeal/MMM-Bose-Soundtouch#1]
Your module is talking to me: "Soundtouch - Your help is needed"

<nowPlaying deviceID="04A316E013EB" source="AMAZON" sourceAccount="MYEMAILADDRESS">
<ContentItem source="AMAZON" type="tracklist" location="catalog/playlists/B071XTDQGM/chunk=0/#playable" sourceAccount="MYEMAILADDRESS" isPresetable="true">
<itemName>Best of Prime Music</itemName>
<containerArt>
https://images-na.ssl-images-amazon.com/images/I/61u7u0OUVgL._SCLZZZZZZZ__SX150_SY150_.jpg
</containerArt>
</ContentItem>
<track>Tired</track>
<artist>Alan Walker & Gavin James</artist>
<album/>
<stationName>Best of Prime Music</stationName>
<art artImageStatus="IMAGE_PRESENT">
https://images-na.ssl-images-amazon.com/images/I/61a9x2LNXuL._SCLZZZZZZZ__.jpg
</art>
<time total="192">9</time>
<skipEnabled/>
<playStatus>PLAY_STATE</playStatus>
<shuffleSetting>SHUFFLE_OFF</shuffleSetting>
<repeatSetting>REPEAT_OFF</repeatSetting>
<skipPreviousEnabled/>
<skipPreviousSupported value="true"/>
<streamType>TRACK_ONDEMAND</streamType>
</nowPlaying>

**Comment by SpoturDeal** [comment]
@LSchuetzi84 Hello Lucas.

Different service give different results could you please send me the file that you get if you enter in your browser http://[ipaddressOfSoundTouch]:8090/now_playing.

[ipaddressOfSoundTouch] needs yo be replaced by your ipnumber (192.168.xxx.xxx)

That will show you XML page could you please copy that info and post it here. I can then adapt the module for amazone

**Comment by LSchuetzi84** [comment]
Hi Carl, 

here you can find the xml content:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<nowPlaying deviceID="04A316E013EB" source="AMAZON" sourceAccount="MYEMAIL">
<ContentItem source="AMAZON" type="tracklist"location="catalog/playlists/B071XTDQGM/chunk=0/#playable"sourceAccount="MYEMAIL" isPresetable="true">
<itemName>Best of Prime Music</itemName>
<containerArt>
https://images-na.ssl-images-amazon.com/images/I/61u7u0OUVgL._SCLZZZZZZZ__SX150_SY150_.jpg
</containerArt>
</ContentItem>
<track>Keine Maschine</track>
<artist>Tim Bendzko</artist>
<album/>
<stationName>Best of Prime Music</stationName>
<art artImageStatus="IMAGE_PRESENT">
https://images-na.ssl-images-amazon.com/images/I/61vaHHj3iSL._SCLZZZZZZZ__.jpg
</art>
<time total="197">0</time>
<skipEnabled/>
<playStatus>PLAY_STATE</playStatus>
<shuffleSetting>SHUFFLE_OFF</shuffleSetting>
<repeatSetting>REPEAT_OFF</repeatSetting>
<skipPreviousEnabled/>
<skipPreviousSupported value="true"/>
<streamType>TRACK_ONDEMAND</streamType>
</nowPlaying>

**Comment by SpoturDeal** [comment]
Hello Lucas,

I have updated the module it should support Amazon now.
You may want to remove your email address from the XML file that you send before. 
Thanks for helping

Carl

**Comment by LSchuetzi84** [comment]
I will update and test it. I have a few services in my Soundtouch. I will give you feedback as soon as possible

**Comment by LSchuetzi84** [comment]
Yeah Thank you! Amazon Prime Music is working fine!
Could you please add TuneIn. Here is my xml file: 

[tunein.txt](https://github.com/SpoturDeal/MMM-Bose-Soundtouch/files/1775637/tunein.txt)

**Comment by SpoturDeal** [comment]
@LSchuetzi84 Hello Lucas,
Just added TuneIn as well. It should now support Spotify, Amazon, Deezer, TuneIn, iTunes and Internet Radio.

Carl

**Comment by LSchuetzi84** [comment]
Yes TuneIn is also working fine. 
Thanks for your help!
