### ISSUE TITLE
No nice message when playing via TV

### ISSUE THREAD

**Issue by bertwest** [SpoturDeal/MMM-Bose-Soundtouch#3]
Hi! 
A very cool Module! Thanks a lot!
I do have a Soundtouch 300 that is connected to a TV.
The MMM shows the following in this state:

```
    Soundtouch - Your help is needed
    			
    Please send me a message with the contents of
    http:/xxx.xxx.xxx.xxx:8090/now_playing
    I can add the unknown service.	
```

Here is what the now_playing file contains:

`<?xml version="1.0" encoding="UTF-8" ?><nowPlaying deviceID="xxxxxxxxxxxxxx" source="PRODUCT" sourceAccount="TV"><ContentItem source="PRODUCT" sourceAccount="TV" isPresetable="false" /><art artImageStatus="SHOW_DEFAULT_IMAGE" /><playStatus>PLAY_STATE</playStatus></nowPlaying>`

I guess and hope this is easy to fix :-)

Best Regards
bertwest

**Comment by SpoturDeal** [comment]
@bertwest 
I have added a new snipplet to the code the message should be gone now.
Best regards

Carl

**Comment by bertwest** [comment]
Looks much better now. Thanks!
Bert

**Comment by SpoturDeal** [comment]
Bose has so much different replies.
They are not published so every new device needs to be added.

**Comment by bertwest** [comment]
Oh. I didn't look into that so far. I just was very pleased that someone had taken some time to develop such a module :smile: 
But well... What came to my mind when I read your replay was this: I don't know how complicated this would be, but how about exposing this topic to the Module User by making it configurable via the MMM config? That way you (as the programmer) would no longer have to take care of that.
