### ISSUE TITLE
Alexa - unknown Service

### ISSUE THREAD

**Issue by LSchuetzi84** [SpoturDeal/MMM-Bose-Soundtouch#4]
Hi, 
I am playing music from my Amazon Music Account on Alexa on my Bose Soundtouch via the Alexa Bose Skill and I am getting a message with an unknown service on my MagicMirror:
XML is attached.
[Alexa.txt](https://github.com/SpoturDeal/MMM-Bose-Soundtouch/files/2519496/Alexa.txt)

**Comment by SpoturDeal** [comment]
Hello  @LSchuetzi84 ,

Just added Alexa, because Alexa is Amazon it will display the Amazon logo

Grüsse

Carl

**Comment by SpoturDeal** [comment]
Thank you

**Comment by cedcas** [comment]
I believe this is related to the ALEXA issue as well as I'm have the same scenario as Carl.  Here's what's in the "*/now_playing"
Echo Dot-3N1Echo Dot-3N1STOP_STATE

**Comment by SpoturDeal** [comment]
@cedcas

If you enter 

`
http://ipaddress_of_your_soundtouch:8090/now_playing
`

in your browser

You get a XML file please post that. (remove the IP address not everyone needs to know)

With this files contents I am able to help you.

**Comment by SpoturDeal** [comment]
No replies from @cedcas and @LSchuetzi84 

I am willing to help everyone, but some extra info might be needed to fix the issue. Especially when I am not able to reproduce the error myself

So this issue is closed.

**Comment by cedcas** [comment]
I have provided the value seen in "http://ipaddress_of_your_soundtouch:8090/now_playing", in my initial comment, which is:

Echo Dot-3N1Echo Dot-3N1STOP_STATE

**Comment by SpoturDeal** [comment]
Echo Dot-3N1Echo Dot-3N1STOP_STATE  is not a reply from BOSE SoundTouch speaker
It looks like it is a reply from your Amazon Echo Dot speaker. That is not compatible with BOSE Soundtouch.
**The BOSE SoundTouch reply with a XML file.**

**Comment by cedcas** [comment]
That is correct, I’m playing my echo dot that’s connected to my Bose SoundTouch. Playing music just on my Bose without echo dot works great, but not when echo dot is in the equation. 

By the way, thanks for the great module!
